CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS facts (
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fact_id VARCHAR(25) NOT NULL,
    -- fact TEXT NOT NULL,
    lang TEXT NOT NULL,
    ts TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, fact_id)
);